### PR TITLE
Install Golang from source

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @mrunalp

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

File: contrib/test/integration/system.yml [hunk 1]
```diff
@@ -1,21 +1,63 @@
...
-    sslverify: no
-  when: ansible_distribution in ['RedHat', 'CentOS']
-
 - name: Make sure we have all required packages
   package:
     name: "{{ item }}"
     state: present
-  with_items: "{{ rpm_pkgs }}"
+  with_items:
+    - btrfs-progs-devel
```
Comment (rhatdan) [inline contrib/test/integration/system.yml]: This package will no longer be in RHEL 7.4.
Why are you reverting this?

Comment (stevekuznetsov) [reply contrib/test/integration/system.yml]: The commit moves it out of `vars` since there's only one place the list is used and it's hard to see what is happening when you install RPMs here. If you'd rather me keep it in `vars` I can. No strong feelings here.

Re: `btrfs-progs-devel` -- I did not remove or add this, just moved it from one place to the other. I was able to install it with `rhel-server-releases-optional` enabled.I can see from my current testing the following are missing in 7.4:

```
npm
python2-mock
python-click
```

I don't really understand why we have those deps at all.
```

Comment (mrunalp) [reply contrib/test/integration/system.yml]: @rhatdan The deps are just being moved around here not re-added. 
@stevekuznetsov I think we should be fine without those dependencies unless ansible needs them for some reason.

Comment (rhatdan) [reply contrib/test/integration/system.yml]: Ok no problem,  @stevekuznetsov, I think @cevich just moved it out, but if it is only used in one place I am fine with moving it.  I have a pull request to remove btrfs from RHEL, but we can wait for that until we have a RHEL7.4 AMI.

File: contrib/test/integration/README.md [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+When running `main.yml`, three tags are present:
+
+ - `setup`: run all tasks to set up the system for testing
+ - `e2e`: build CRI-O from source and run Kubernetes node E2Es
+ - `integration`: build CRI-O from source and run the local integration suite
+
+The playbooks assume the following things about your system:
+
+ - the `$GOPATH` is set and present for all shells (*e.g.* written in `/etc/environment`)
+ - CRI-O is checked out to the correct state at `${GOPATH}/src/github.com/kubernetes-incubator/cri-o`
```
Comment (stevekuznetsov) [inline contrib/test/integration/README.md]: @cevich @mrunalp this chicken-and-egg situation is why having the job def deal with this sort of set-up is kind of weird. But I think we can live with it. I've re-thought some of the jobs I wrote to be more lean. Now there are basically four steps to all the jobs:

 - set up the user that our CI expects to use
 - install ansible and make sure ansible can work against `localhost`
 - create $GOPATH and clone CRI-O
 - run the `main.yml` playbook with the correct tags

Hopefully this will make it easier for y'all to have a self-sufficient playbook and make it clearer what the hidden dependencies are.

**Comment by stevekuznetsov** [comment]
@cevich usually in our CI env we run with two Ansible output plugins:

 - [`default_with_output_lists.py`](https://github.com/openshift/origin-ci-tool/blob/master/oct/ansible/oct/callback_plugins/default_with_output_lists.py): ensures `stderr` and `stdout`, if present, are lists of lines and not one massive block with inline `\n` chars
 - [`generate_junit.py`](https://github.com/openshift/origin-ci-tool/blob/master/oct/ansible/oct/callback_plugins/generate_junit.py): generated jUnit output for each task so you can quickly identify which task failed

I'm not entirely sure how they will play with your plugins that you added here, but it looks like you've made it so there is a local `ansible.cfg` that makes it hard to load these. Let's chat on how to best integrate these two features.  I find the two we enable to be invaluable in getting the correct info to devs.

**Comment by stevekuznetsov** [comment]
@cevich also from the current output plugin I see:

```
STDERR:
---
No handlers could be found for logger "dnf"

---
```

**Comment by stevekuznetsov** [comment]
@cevich also the output plugin seems to go haywire on some outputs...

<details>
<summary>an example:</summary>

```
TASK [build kubernetes] ********************************************************
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/build/kubernetes.yml:14
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": "/bin/make", 
    "failed": true, 
    "rc": 2
}

STDERR:
---
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:619 kube::golang::setup_env(...)
!!! [0930 21:24:49]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2

---

MSG:
---
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:619 kube::golang::setup_env(...)
!!! [0930 21:24:49]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0930 21:24:49] Call tree:
!!! [0930 21:24:49]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
```

</details>

**Comment by stevekuznetsov** [comment]
The two AMI jobs failed but due to AWS flakes around AMI creation... using those AMIs though now we can

/test all

**Comment by stevekuznetsov** [comment]
AWS provisioning is flaking out ... not reproducing that locally..

/test all

**Comment by stevekuznetsov** [comment]
Fedora AMI had the `grubby` call which made it not boot. Trying again with the conditional logic. RHEL AMI looks good -- local integration tests succeeded.

**Comment by stevekuznetsov** [comment]
OK, lets try tests with the new Fedora AMI

/test fedora

**Comment by stevekuznetsov** [comment]
E2Es only fail on Guestbook! This is good.

Looking into Fedora integration test.

**Comment by mrunalp** [comment]
@stevekuznetsov Nice! Getting close :)
BTW I noticed that the e2e tests are running twice? Used to 148/149 but is 296/298 now.

**Comment by stevekuznetsov** [comment]
@mrunalp we're just getting 2x the jUnit because of the result grabbing playbook

**Comment by stevekuznetsov** [comment]
@mrunalp Fedora integration is failing on:

```
./test/test_runner.sh 
awk: fatal: cannot open file `/etc/selinux//contexts/lxc_contexts' for reading (No such file or directory)
make: *** [Makefile:125: localintegration] Error 2
```

100% reproducible Thoughts?

**Comment by stevekuznetsov** [comment]
Maybe fixed the double-reporting of jUnit

/test all

**Comment by mrunalp** [comment]
@stevekuznetsov Do we have these rpms?
```
[root@localhost ~]# rpm -qf /etc/selinux/targeted/
selinux-policy-targeted-3.13.1-260.8.fc26.noarch
[root@localhost ~]# rpm -qf /etc/selinux/
libsemanage-2.6-4.fc26.x86_64
selinux-policy-3.13.1-260.8.fc26.noarch
[root@localhost ~]# 
```

**Comment by stevekuznetsov** [comment]
@mrunalp you can always see what's installed by looking at `artifacts/generated/installed_packages.log` as in [here](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/kubernetes-incubator_cri-o/963/test_pull_request_crio_integration_fedora/65/artifacts/generated/installed_packages.log):

```
libselinux.x86_64                          2.6-7.fc26                  @updates 
libselinux-devel.x86_64                    2.6-7.fc26                  @updates 
libselinux-python.x86_64                   2.6-7.fc26                  @updates 
libselinux-python3.x86_64                  2.6-7.fc26                  @updates 
libselinux-utils.x86_64                    2.6-7.fc26                  @updates 
libsemanage.x86_64                         2.6-4.fc26                  @anaconda
libsemanage-python3.x86_64                 2.6-4.fc26                  @anaconda
libsepol.x86_64                            2.6-2.fc26                  @updates 
libsepol-devel.x86_64                      2.6-2.fc26                  @updates 
selinux-policy.noarch                      3.13.1-260.9.fc26           @updates 
selinux-policy-targeted.noarch             3.13.1-260.9.fc26           @updates 
```

**Comment by stevekuznetsov** [comment]
Daily AMI jobs overwrote the latest available AMIs ;) oh my

**Comment by mrunalp** [comment]
@stevekuznetsov The SELinux error is coming from this line https://github.com/kubernetes-incubator/cri-o/blob/master/test/helpers.bash#L83
So, I think that /etc/selinux/config file is either missing or doesn't SELINUXTYPE set correctly. 
This is what it looks like locally for me:
```
[root@localhost ~]# cat /etc/selinux/config                                           

# This file controls the state of SELinux on the system.                              
# SELINUX= can take one of these three values:                                        
#     enforcing - SELinux security policy is enforced.                                
#     permissive - SELinux prints warnings instead of enforcing.                      
#     disabled - No SELinux policy is loaded.                                         
SELINUX=enforcing                          
# SELINUXTYPE= can take one of these three values:                                    
#     targeted - Targeted processes are protected,                                    
#     minimum - Modification of targeted policy. Only selected processes are protected.                                                                                      
#     mls - Multi Level Security protection.                                          
SELINUXTYPE=targeted                       
```

**Comment by stevekuznetsov** [comment]
Wow. Unclear how _this_ happened...

```
[root@ip-172-18-13-87 ~]# cat /etc/selinux/config
# This file controls the state of SELinux on the system.# SELINUX= can take one of these three values:#     enforcing - SELinux security policy is enforced.#     permissive - SELinux prints warnings instead of enforcing.#     disabled - No SELinux policy is loaded.SELINUX=permissive# SELINUXTYPE= can take one of these three values:#     targeted - Targeted processes are protected,#     minimum - Modification of targeted policy. Only selected processes are protected. #     mls - Multi Level Security protection.SELINUXTYPE=targeted[root@ip-172-18-13-87 ~]#
```

**Comment by stevekuznetsov** [comment]
We _do_ touch it using Ansible during the setup:

```
TASK [disable selinux see https://github.com/kubernetes-incubator/cri-o/issues/528] ***
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/system.yml:91
changed: [localhost] => {
    "changed": true, 
    "configfile": "/etc/selinux/config", 
    "failed": false, 
    "policy": "targeted", 
    "state": "permissive"
}

MSG:
---
runtime state changed from 'enforcing' to 'permissive', config state changed from 'enforcing' to 'permissive'
---
```

But I've never seen that happen before. Let's try re-creating the AMI and determine if it's still broken.

/test ami_fedora

**Comment by stevekuznetsov** [comment]
The base Fedora image you made, @mrunalp , has a correct config:

```
[root@ip-172-18-8-151 ~]# cat /etc/selinux/config 

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=enforcing
# SELINUXTYPE= can take one of these three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted


```

**Comment by mrunalp** [comment]
Not sure how it got corrupted. We don't write to it in crio or the tests AFAIK.

**Comment by stevekuznetsov** [comment]
Yeah, something in the playbooks is definitely corrupting it. Just confirmed with the newer AMI. Weird.

**Comment by stevekuznetsov** [comment]
Removed the SELinux disabling since the issue is closed anyway...

/test ami_fedora

**Comment by mrunalp** [comment]
integration tests seem to be running okay. At 38 right now..

**Comment by stevekuznetsov** [comment]
On the E2E suite now... yeah so I guess Ansible was corrupting the file.

**Comment by stevekuznetsov** [comment]
Manually bumped that AMI to ready,

/test fedora

**Comment by rhatdan** [comment]
SELinux issue looks like selinux-policy was not installed?

**Comment by stevekuznetsov** [comment]
@rhatdan Ansible was corrupting `/etc/selinux/config`

Rebased on master, 

/test ami

**Comment by stevekuznetsov** [comment]
@rhatdan not sure your patch works

```

TASK [build cri-o] *************************************************************
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/build/cri-o.yml:18
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": "/bin/make", 
    "failed": true, 
    "rc": 2
}

STDOUT:
---
go build -ldflags '-X main.gitCommit="40132d786d437b6e379ae2aa10dce9d71244c07b" -X main.buildInfo=1506957016 -X main.version=1.0.0-rc3-dev -X main.kpodVersion=0.1' -tags "selinux seccomp btrfs_noversion " -o crio github.com/kubernetes-incubator/cri-o/cmd/crio

---

STDERR:
---
# github.com/kubernetes-incubator/cri-o/vendor/github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:8:25: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
                         ^
compilation terminated.
make: *** [crio] Error 2

---
```

**Comment by mrunalp** [comment]
We can revert https://github.com/kubernetes-incubator/cri-o/commit/6866589be7baa243a10c884108eb597913dd9164 in this PR.

**Comment by mrunalp** [comment]
LGTM. The RHEL failures are due to #948.

**Comment by rhatdan** [comment]
@mrunalp @nalind That is strange.  This means the tool that decided whether or not you had btrfs support was not working correctly.

 cat hack/btrfs_tag.sh 
#!/bin/bash
cc -E - > /dev/null 2> /dev/null << EOF
#include <btrfs/version.h>
EOF
if test $? -ne 0 ; then
	echo btrfs_noversion
fi


This should fail which should cause containers storage to not attempt to build btrfs support on RHEL7 systems.

**Comment by nalind** [comment]
That's only determining if the btrfs headers defined a couple of version macros, and doesn't control whether or not we attempt to build with support for btrfs.
